# Generated by Django 3.1.4 on 2020-12-12 21:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='selfParent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selfChildren', to='navi.laboratory'),
        ),
        migrations.AddField(
            model_name='preparation',
            name='selfParent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selfChildren', to='navi.preparation'),
        ),
        migrations.AlterField(
            model_name='agrohym',
            name='nowTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 13, 3, 12, 6, 85576), null=True),
        ),
        migrations.AlterField(
            model_name='agrohym',
            name='samples',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agrohym', to='navi.samples'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='nowTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 13, 3, 12, 6, 85576), null=True),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='samples',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratory', to='navi.samples'),
        ),
        migrations.AlterField(
            model_name='preparation',
            name='nowTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 13, 3, 12, 6, 85576), null=True),
        ),
        migrations.AlterField(
            model_name='preparation',
            name='samples',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparation', to='navi.samples'),
        ),
        migrations.AlterField(
            model_name='selection',
            name='nowTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 13, 3, 12, 6, 84543), null=True),
        ),
        migrations.AlterField(
            model_name='selection',
            name='samples',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selection', to='navi.samples'),
        ),
    ]
