# Generated by Django 3.1.4 on 2020-12-12 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navi', '0002_auto_20201213_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agrohym',
            name='nowTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 13, 3, 16, 43, 803425), null=True),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='nowTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 13, 3, 16, 43, 802428), null=True),
        ),
        migrations.AlterField(
            model_name='preparation',
            name='nowTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 13, 3, 16, 43, 802428), null=True),
        ),
        migrations.AlterField(
            model_name='selection',
            name='nowTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 13, 3, 16, 43, 801433), null=True),
        ),
    ]
