# Generated by Django 3.1.4 on 2020-12-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navi', '0007_auto_20201215_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agrohym',
            name='nowTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='nowTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='preparation',
            name='nowTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='selection',
            name='nowTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
