# Generated by Django 3.1.4 on 2020-12-19 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navi', '0010_elementsname_basic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('status', models.CharField(choices=[('Поступило', 'Поступило'), ('Готово', 'Готово')], default='Поступило', max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corms', to='navi.client')),
            ],
            options={
                'verbose_name': 'Корм',
                'verbose_name_plural': 'Корма',
            },
        ),
    ]
