# Generated by Django 3.1.4 on 2020-12-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navi', '0011_corms'),
    ]

    operations = [
        migrations.AddField(
            model_name='corms',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
