# Generated by Django 3.1.4 on 2020-12-20 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navi', '0012_corms_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='corms',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='navi.corms'),
        ),
    ]
