# Generated by Django 3.1.4 on 2020-12-20 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navi', '0013_corms_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corms',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='navi.corms'),
        ),
    ]
