# Generated by Django 3.1.4 on 2020-12-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navi', '0017_remove_clientcorm_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='nowTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='clientcorm',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientcorm',
            name='nowTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='samples',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samples',
            name='nowTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
